#!/bin/sh

# PROVIDE: cinder-volume 
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="cindervolume"
rcvar=cindervolume_enable

load_rc_config $name
: ${cindervolume_enable:=yes}
: ${cindervolume_user:=dynavisor}


command="/usr/local/bin/python"
command_args="2>/dev/null&" 

start_precmd="${name}_prestart"

cindervolume_prestart()
{
    rc_flags="/opt/stack/cinder/bin/cinder-volume --config-file /usr/local/etc/cinder/cinder.conf ${rc_flags}"
    return 0
}

run_rc_command "$1"
