#!/bin/sh

# PROVIDE: nova-api-metadata
# REQUIRE: LOGIN mysql
# KEYWORD: shutdown

. /etc/rc.subr

name="novaapimetadata"
rcvar=novaapimetadata_enable

load_rc_config $name

command="/usr/local/bin/nova-api-metadata"
command_args="2>/dev/null&"
command_interpreter=/usr/local/bin/python2.7

run_rc_command "$1"
