#!/bin/sh

# PROVIDE: swift-object-server
# REQUIRE: keystone
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="swiftobjectserver"
rcvar=swiftobjectserver_enable

load_rc_config $name
: ${swiftobjectserver_enable:=yes}

command="/usr/local/bin/python"
command_args="2>/dev/null&" 

start_precmd="${name}_prestart"

swiftobjectserver_prestart()
{
    rc_flags="/opt/stack/swift/bin/swift-object-server /etc/swift/object-server/1.conf ${rc_flags}"
    return 0
}


run_rc_command "$1"
