#!/bin/sh

# PROVIDE: swift-container-server
# REQUIRE: keystone
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="swiftcontainerserver"
rcvar=swiftcontainerserver_enable

load_rc_config $name
: ${swiftcontainerserver_enable:=yes}

command="/usr/local/bin/python"
command_args="2>/dev/null&" 

start_precmd="${name}_prestart"

swiftcontainerserver_prestart()
{
    rc_flags="/opt/stack/swift/bin/swift-container-server /etc/swift/container-server/1.conf ${rc_flags}"
    return 0
}


run_rc_command "$1"
