#!/bin/sh

# PROVIDE: cinder-api 
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="cinderapi"
rcvar=cinderapi_enable

load_rc_config $name
: ${cinderapi_enable:=yes}
: ${cinderapi_user:=dynavisor}

command="/usr/local/bin/python"
command_args="2>/dev/null&" 

start_precmd="${name}_prestart"

cinderapi_prestart()
{
    rc_flags="/opt/stack/cinder/bin/cinder-api --config-file /usr/local/etc/cinder/cinder.conf ${rc_flags}"
    return 0
}

run_rc_command "$1"
