#!/bin/sh

# PROVIDE: keystone
# REQUIRE: LOGIN mysql
# BEFORE: nova-api 
# KEYWORD: shutdown

. /etc/rc.subr

name=keystone
rcvar=keystone_enable

command="/usr/local/bin/python"
command_args="2>/dev/null&" 

start_precmd="${name}_prestart"

keystone_prestart()
{
    rc_flags="/opt/stack/keystone/bin/keystone-all --config-file /etc/keystone/keystone.conf ${rc_flags}"
    return 0
}


load_rc_config $name
: ${keystone_enable:=yes}
run_rc_command "$1"
