#!/bin/sh

# PROVIDE: nova-conductor 
# REQUIRE: nova-api LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="novaconductor"
rcvar=novaconductor_enable

load_rc_config $name
: ${novaconductor_enable:=yes}
: ${novaconductor_user:=dynavisor}

command="/usr/local/bin/nova-conductor"
command_args="2>/dev/null&"
command_interpreter=/usr/local/bin/python2.7

start_precmd="${name}_prestart"

novaconductor_prestart()
{
    rc_flags="--config-file /usr/local/etc/nova/nova.conf ${rc_flags}"
    return 0
}


run_rc_command "$1"
