#!/bin/sh

# PROVIDE: nova-novncproxy 
# REQUIRE: nova-api LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="novanovncproxy"
rcvar=novanovncproxy_enable

load_rc_config $name
: ${novanovncproxy_enable:=yes}
: ${novanovncproxy_user:=dynavisor}

command="/usr/local/bin/nova-novncproxy"
command_args="&"
command_interpreter=/usr/local/bin/python2.7

start_precmd="${name}_prestart"

novanovncproxy_prestart()
{
    rc_flags="--config-file /usr/local/etc/nova/nova.conf --web /opt/stack/noVNC ${rc_flags}"
    if ! checkyesno novaapi_enable && \
	    ! /usr/local/etc/rc.d/nova-api forcestatus 1>/dev/null 2>&1; then
	force_depend novaapi || return 1
    fi
    return 0
}

run_rc_command "$1"
