#!/bin/sh

# PROVIDE: nova-scheduler 
# REQUIRE: nova-api LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="novascheduler"
rcvar=novascheduler_enable

load_rc_config $name
: ${novascheduler_enable:=yes}
: ${novascheduler_user:=dynavisor}

command="/usr/local/bin/nova-scheduler"
command_args="2>/dev/null&"
command_interpreter=/usr/local/bin/python2.7
start_precmd="${name}_prestart"

novascheduler_prestart()
{
    rc_flags="--config-file /usr/local/etc/nova/nova.conf ${rc_flags}"
    if ! checkyesno novaapi_enable && \
	    ! /usr/local/etc/rc.d/nova-api forcestatus 1>/dev/null 2>&1; then
	force_depend novaapi || return 1
    fi
    return 0
}

run_rc_command "$1"
