#!/bin/sh

# PROVIDE: swift-account-server
# REQUIRE: keystone
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="swiftaccountserver"
rcvar=swiftaccountserver_enable

load_rc_config $name
: ${swiftaccountserver_enable:=yes}

command="/usr/local/bin/python"
command_args="2>/dev/null&" 

start_precmd="${name}_prestart"

swiftaccountserver_prestart()
{
    rc_flags="/opt/stack/swift/bin/swift-account-server /etc/swift/account-server/1.conf ${rc_flags}"
    return 0
}


run_rc_command "$1"
